# Use the latest 2.1 version of CircleCI pipeline process engine
version: 2.1

jobs:
  # Define a job to say "Hello, World!"
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  # SonarQube scan job
  sonarqube:
    working_directory: ~/build
    docker:
      - image: circleci/node:16  # More comprehensive image
    resource_class: small
    steps:
      - checkout
     - run: |
    echo "Setting SonarQube branch"
    SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
    echo "Sonar branch value is: $SONAR_BRANCH"
    echo "Sonar organization value is: $SONAR_ORG"
    echo "Sonar project key value is: $SONAR_PROJECT_KEY"
    echo "Running SonarQube scan..."
    sonar-scanner \
      -Dsonar.projectKey="${SONAR_PROJECT_KEY}" \
      -Dsonar.organization="${SONAR_ORG}" \
      -Dsonar.host.url="https://sonarcloud.io" \
      -Dsonar.login="${SONAR_TOKEN}" \
      -Dsonar.branch.name="${SONAR_BRANCH}" \
      -Dsonar.sources="." \
      -Dsonar.exclusions="**/android/**,**/ios/**"

# Define workflows
workflows:
  build-and-scan:
    jobs:
      - say-hello
      - sonarqube
