version: 2.1

jobs:
  # Job to print "Hello, World!"
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  # SonarQube scan job using a pre-built Docker image
  sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli:latest  # Using SonarQube CLI image
    resource_class: small
    steps:
      - checkout
      - run:
          name: Verify Environment Variables
          command: |
            echo "Sonar branch value: ${CIRCLE_BRANCH}"
            echo "Sonar organization: ${SONAR_ORG}"
            echo "Sonar project key: ${SONAR_PROJECT_KEY}"
      - run:
          name: Run SonarQube Scan
          command: |
            export SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Running SonarQube scan on branch: ${SONAR_BRANCH}"
            sonar-scanner \
              -Dsonar.projectKey="${SONAR_PROJECT_KEY}" \
              -Dsonar.organization="${SONAR_ORG}" \
              -Dsonar.host.url="https://sonarcloud.io" \
              -Dsonar.login="${SONAR_TOKEN}" \
              -Dsonar.branch.name="${SONAR_BRANCH}" \
              -Dsonar.sources="." \
              -Dsonar.exclusions="**/android/**,**/ios/**"

workflows:
  build-and-scan:
    jobs:
      - say-hello
      - sonarqube
